# Generated by Django 5.1 on 2024-08-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('OPERATOR', 'Operator'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=15),
        ),
    ]
