# Generated by Django 5.1 on 2024-08-27 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_busoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOperatorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='operator_images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.busoperator')),
            ],
        ),
    ]
