# Generated by Django 5.1 on 2024-08-27 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_schedule_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='buses.bus'),
        ),
    ]
