# Generated by Django 5.1 on 2024-08-31 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_alter_payment_user'),
        ('users', '0004_busoperatorimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=2560)),
                ('reference', models.CharField(max_length=10)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.busoperator')),
            ],
        ),
    ]
