# Generated by Django 5.1 on 2024-09-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0009_withdrawals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['created_at']},
        ),
    ]
