# Generated by Django 5.1 on 2024-09-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notifications_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='recipients',
            new_name='recipient',
        ),
    ]
